### ISSUE TITLE
Make tags board-exclusive

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#140]
# 🌟 Feature
It would be nice if the tags were not global but stayed attached to their boards. For example, my Nintendo Switch has tags for physical copies, US eShop, UK eShop, etc. which are useless on other boards.

Ideally, it would be nice to have global tags and board-exclusive tags but that might create a lot of confusion. Not sure how to implement it best.

**Comment by romancm** [comment]
Existing tags will remain available and will be labeled "global tags", platform-specific tags will be named accordingly.

**Comment by areyouokani** [comment]
Great option, thank you!

**Comment by romancm** [comment]
Fixed in https://github.com/romancm/gamebrary/releases/tag/v2.6.3
