### ISSUE TITLE
The new "add game" button interferes with the UI in text-only mode

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#141]
# Bug report

## Description of the problem
The "move" anchor on the card gets hid behind the "add game" button in the text-only mode.
### Additional info (optional)
You can still move the card if you pixel-hunt for the anchor but it is definitely inconvenient.
### Screenshots (optional)
![image](https://user-images.githubusercontent.com/29702693/66031227-a65ca080-e50b-11e9-9590-004462be4290.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome 76.0.3809.132 | 
| Operating System |  Ubuntu 18.04 |

**Comment by romancm** [comment]
Fixed in https://github.com/romancm/gamebrary/commit/5f7155c53ad9a0a2fa65f0609e1401bdb42c965f

Reopening until deployed

**Comment by romancm** [comment]
Deployed in https://github.com/romancm/gamebrary/releases/tag/v2.5.4
