### ISSUE TITLE
No "move" anchor in the Grid mode

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#142]
# Bug report

## Description of the problem
There is no way to move a card from one list to the next when they are in Grid mode. 

### Additional info (optional)
If the anchor was removed intentionally, then there needs to be an alternative. And it might be me but I don't see it.

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/29702693/66031497-369ae580-e50c-11e9-90b6-ae4a14750435.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome 76.0.3809.132 | 
| Operating System |  Ubuntu 18.04 |

### To do
- [ ] Upgrade vue-draggable to latest version
- [ ] Restore dragging capabilities to grid view

**Comment by romancm** [comment]
https://www.npmjs.com/package/vue-packery-plugin
