### ISSUE TITLE
Allow users to add games from any system into a general list

### ISSUE THREAD

**Issue by paddykontschak** [romancm/gamebrary#163]
# 🌟 Feature

## Reason
A coworker told me he tried Gamebrary and was confused why he couldn't add Gris into his Steam gameboard lists. He verified that Gris was in IGDB but the search still wouldn't show any results.

I told him to check if the game was in the Microsoft gameboard and he was able to add it there. IGDB generally doesn't seem to have clear guidelines for Steam vs Windows/Linux/Mac and it often happens that people just add games under Windows or Steam.

## Suggestion
Would it be possible to add a cross-platform board where users can just add any games they ever played, regardless of the platform?

## Additional (optional?) Features
Once the user has too big of a cross-platform board they could break off that board; copying all the lists in which games were added and pasting them into their respective platform-specific boards (maybe checking list names and fusing them, but just adding the whole list would also suffice).

Thoughts?

**Comment by romancm** [comment]
I think `Microsoft` and `Steam` platforms should be merged into a single PC platform. I don't think most users will care where the game comes from as long as its for modern PC gaming.

**Comment by romancm** [comment]
If users wanted to differentiate where the pc game came from they can always use tags for `steam` `epic store` or whatever.

**Comment by romancm** [comment]
Cross-platform board can also be added. I also wanted add an option to create more than 1 board per platform.
