### ISSUE TITLE
Unable to find "Divinity: Original Sin II - Definitive Edition" in Switch gameboard

### ISSUE THREAD

**Issue by paddykontschak** [romancm/gamebrary#171]
# Bug report

## Description of the problem
I'm unable to find [Divinity: Original Sin II - Definitive Edition](https://www.igdb.com/games/divinity-original-sin-ii-definitive-edition) when trying to add it to any of my lists in the Switch gameboard. I don't have that problem with any other Switch games.

### Additional info (optional)

Game's IGDB page has the following information in the About section:
> Platforms: Mac, Xbox One, PC (Microsoft Windows), PlayStation 4

And the following information in the sidebar below the screenshots and videos:

> Information
> Release Dates:
> Aug 31, 2018 - PlayStation 4
> Aug 31, 2018 - Xbox One
> Aug 31, 2018 - PC (Microsoft Windows)
> Jan 31, 2019 - Mac
> Sep 04, 2019 - Nintendo Switch

### Screenshots (optional)
![Screenshot 2020-01-15 at 1 45 57 PM](https://user-images.githubusercontent.com/984069/72435040-6ad5a180-379d-11ea-9508-613dc8d70863.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Firefox 72.0.1 |

**Comment by romancm** [comment]
Reported issue in IGDB's #api-bug-reports discord channel

**Comment by gamebrary** [comment]
![Screenshot from 2020-07-21 13-50-29](https://user-images.githubusercontent.com/60666270/88105971-96c14d80-cb59-11ea-92da-395cf26908b6.png)
looks like IGDB added it finally, closing this.
