### ISSUE TITLE
Lists won't load

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#177]
# Bug report
## Description of the problem
Something is very much borken since like 95% of the time I can not load my game lists.
 
### Additional info (optional)
Some of them load on my PC, but don't load on mobile. Some otherwise, work on mobile but don't load on PC.
 
### Screenshots (optional)
Working:
![image](https://user-images.githubusercontent.com/29702693/73246064-61453400-41b6-11ea-94e4-eb82a8251dbb.png)
Not working (Should have an empty "Unsorted" list. I also tried creating new lists, still won't appear):
![image](https://user-images.githubusercontent.com/29702693/73246081-6b673280-41b6-11ea-8d9d-85886e1fce45.png)

### Your Environment
Chrome on Ubuntu Linux, Chrome on Android. Tried disabling Adblock, didn't help.

**Comment by romancm** [comment]
@areyouokani I just tested the site and it seems to be working fine. A few defects were introduced recently but I think they're all fixed, can you try clearing your browser's cache and try again? (opening site in incognito window should work if you don't want to clear your cache) Also, could you check in the browser's console and see if there's any errors?

**Comment by romancm** [comment]
Fixed in https://github.com/romancm/gamebrary/pull/178 and deployed in [v2.12.1](https://github.com/romancm/gamebrary/releases/tag/v2.12.1)
