### ISSUE TITLE
More auth options

### ISSUE THREAD

**Issue by romancm** [romancm/gamebrary#187]
**Is your feature request related to a problem? Please describe.**
Currently we only allow accounts from google, open to other platforms as well.

**Describe the solution you'd like**
Since we are using firebase auth we are limited to the following platforms:

- Email/Password
- Phone
- Google [IN USE]
- Play Games
- Game Center
- Beta
- Facebook
- Twitter
- GitHub
- Yahoo
- Microsoft
- Apple
- Anonymous
- Steam

**Describe alternatives you've considered**

**Additional context**

**Comment by paddykontschak** [comment]
Are multiple auth options possible for a given user?

e.g. let the user log in with Google and link their Twitter so they can now also log in with their Twitter.

Gamers would probably also like to log in with Steam and similar gaming accounts. A quick search revealed [this repo](https://github.com/Kamshak/firebase-steam-login). Maybe it's possible to use this in Gamebrary (if it still works) or implement our own solution. Maybe even with other non-steam services.

**Comment by romancm** [comment]
>Are multiple auth options possible for a given user?


Firebase has a setting that can determine that behavior.

<img width="967" alt="Screen Shot 2020-02-03 at 10 53 15 AM" src="https://user-images.githubusercontent.com/645310/73677451-8385f880-4673-11ea-9731-c00db4f0fa8b.png">
<img width="542" alt="Screen Shot 2020-02-03 at 10 53 25 AM" src="https://user-images.githubusercontent.com/645310/73677453-8385f880-4673-11ea-9096-25bb579aee2a.png">
