### ISSUE TITLE
Games on old lists won't show after one of the latest updates

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#195]
**Describe the bug**
I can't see my games, although they are listed in the list. It may have happened with the latest update or the previous one. New lists are working fine, as well as some old ones, but not all.

**To Reproduce**
1. Open the list.
2. See no games.
3. [Oh nosa.jpg](https://pbs.twimg.com/profile_images/788571049499779072/vf_Ifxnw_400x400.jpg)

**Expected behavior**
Seeing my games on the board.

**Screenshots**
![image](https://user-images.githubusercontent.com/29702693/74930916-3fbb1f00-53e7-11ea-8621-5cc39fc15d10.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 76

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Max 2
 - OS: Android 8
 - Browser: Chrome
 - Version: 80

**Additional context**
No idea when it broke, haven't used Gamebrary in a week or two... or three...

**Comment by areyouokani** [comment]
Just removed all my lists from another affected board and created them once more. The problem persists.

**Comment by romancm** [comment]
@areyouokani can you do me a favor and open the browser console and share any errors that may be shown?

**Comment by areyouokani** [comment]
The console in Chrome is empty, no errors at all. However, this might be of interest:
![Без имени](https://user-images.githubusercontent.com/29702693/75430198-ab573c00-5953-11ea-887e-cab729a6567d.png)

**Comment by paddykontschak** [comment]
Could you try opening the app in a private window? Maybe one of your extensions is doing something it shouldn't.

**Comment by jgwehr** [comment]
I've been having this same issue. It seems specific to the **PC** board. My Switch and Ps4 boards have no issues.

This happens in FF, but I also tried in Edge since I have no extensions installed. (my Pi-hole was also disabled)

![ZwGBa8D218](https://user-images.githubusercontent.com/13216529/89193561-c6b21d00-d56b-11ea-9ffd-39cfa7425b9b.gif)


Windows 10
Edge and Firefox 79.0 64bit

**Comment by romancm** [comment]
@jgwehr @areyouokani I finally found the issue, it's a missing null check in the list settings. I will have the fix in the next release, hopefully today or tomorrow I should be able to deploy and get this out.

**Note: your data is there, it's just not displaying because of a javascript error.**

**Comment by romancm** [comment]
@jgwehr @areyouokani this shouldn't be a problem anymore, I just released [v3.0](https://github.com/romancm/gamebrary/releases/tag/v3.0.0) 

You should be able to access your platforms but I strongly suggest you convert them to "boards" using the new UI.

Closing this for now, please let me know if you encounter any issues.
