### ISSUE TITLE
New Platforms

### ISSUE THREAD

**Issue by Bagerian** [romancm/gamebrary#197]
Hi,

Could you add PS5 and Xbox Series X to the list of available platforms? I know they are not out yet but I would like to create wishlists of games I want to buy once they are released : ) 

Thanks!

**Comment by romancm** [comment]
Thanks for reporting this, looks like IGDB already has both platforms available. In the next major release we are going to change the way boards are created, you will be able to select from ALL supported platforms (including ps4 and xbsx).

@all-contributors please add @Bagerian for bug

**Comment by romancm** [comment]
Note: also adding Stadia

**Comment by romancm** [comment]
Fixed in newest version: https://github.com/romancm/gamebrary/releases/tag/v3.0.0
