### ISSUE TITLE
Some recomendations

### ISSUE THREAD

**Issue by vman88** [romancm/gamebrary#206]
- Not all the games load (1.couldn't find Resident Evil: Origins, 2. There are duplicates (e.g. Ni No kuni), 3. Some dual packs (Baulders Gate 1+2, Child of Light/Valiant Heartsare separated).

- Ability to sort after list is created - FIXED

- Export options for shared link to show friends and export to document like PDF

- Displaying Metacritic score

- Ability to sort by tags or show lists by tags

**Comment by romancm** [comment]
@all-contributors please add @vman88 for ideas and bug

**Comment by gamebrary** [comment]
@vman88 closing issue in favor of separate issues. See notes below.

>Not all the games load (1.couldn't find Resident Evil: Origins, 2. There are duplicates (e.g. Ni No kuni), 3. Some dual packs (Baulders Gate 1+2, Child of Light/Valiant Heartsare separated).
All data is obtained from IGDB's API (now owned by twitch), any data duplication, missing titles, etc.

> Ability to sort after list is created - FIXED

👍 

>Export options for shared link to show friends and export to document like PDF

CSV import/export is in the works.

>Displaying Metacritic score

There's no official metacritic API as of right now. Will keep in the backlog.

>Ability to sort by tags or show lists by tags

Added to backlog
