### ISSUE TITLE
Cannot Edit or Delete Tags

### ISSUE THREAD

**Issue by game220** [romancm/gamebrary#210]
ID: S5hJr5E7tiPP0FCipny22LlMLvX2

When trying to edit or delete a tag, I get the following error in console and the application starts failing to respond.

Uncaught (in promise) TypeError: t.$store.dispatch(...) is undefined
    a TagsSettings.vue:303
    w runtime.js:62
    _invoke runtime.js:296
    e runtime.js:114
    r asyncToGenerator.js:17
    default asyncToGenerator.js:35
    e _export.js:36
    default asyncToGenerator.js:14
    saveTags TagsSettings.vue:319
    deleteTag TagsSettings.vue:289
    click TagsSettings.vue:5
    VueJS 3
    i raven.js:376
TagsSettings.vue:303

**Comment by game220** [comment]
I did also try deleting my account and remaking it, but that seems to have not worked. I did also notice that after deleting my account, my new account had my old tags, and the Date Joined was still same.

**Comment by gamebrary** [comment]
@all-contributors please add @game220 for bug

**Comment by gamebrary** [comment]
@game220 Fix for tag editing issue has been deployed. Also, I opened a separate ticket to improve account deleting. Closing this ticket, feel free to reopen if issue persists.
