### ISSUE TITLE
The icon isn't seen on mobile

### ISSUE THREAD

**Issue by erbilnas** [romancm/gamebrary#223]
I added Gamebrary to my home screen like an app on mobile, but the icon shows up as a white box to show any pictures or anything else.

[https://photos.app.goo.gl/Kp8hbdE35Jh6rS469](url)

 - Device: Xiaomi Mi MIX 2
 - OS: Android 9
 - Browser: MS Edge

**Comment by gamebrary** [comment]
Issue has been resolved, thanks for reporting.

**Comment by gamebrary** [comment]
@all-contributors please add @erbilnas for bug
