### ISSUE TITLE
The app.gamebrary.com website doesnt load

### ISSUE THREAD

**Issue by Dinth** [romancm/gamebrary#234]
**Describe the bug**
The website doesnt open.
fs.js file errors with 404 error.

**To Reproduce**
1. Open https://app.gamebrary.com

**Expected behavior**
A website should show up. 

**Screenshots**
![Screenshot 2021-07-18 at 18 02 15](https://user-images.githubusercontent.com/313674/126075901-88b61d49-ef86-462a-b16a-1939310724a1.png)

**Additional context**

**Comment by gamebrary** [comment]
The fix has been deployed. Thank you so much for reporting, I made a mistake that caused a blank page when not logged in.

**Comment by gamebrary** [comment]
@all-contributors please add @Dinth for bug
