### ISSUE TITLE
There's no way to edit game lists

### ISSUE THREAD

**Issue by rllaquet** [romancm/gamebrary#239]
**Describe the bug**
No way to edit lists. Can't see "List settings" button that was available before, so I can't edit the information shown on my lists (for instance show the number of games in a list, or show tags).
Checked if this was a design choice but couldn't find anything related to it on the changelog, last time this was referenced is on v3.8.5 and it's shown as a feature.

**To Reproduce**
1. Go to any board on any account on any browser on any device (tried Firefox on Android, Firefox and Chrome on Linux)
2. Click on the three-dot menu of any game list
4. "List settings" is not available

**Expected behavior**
There's a way to edit game lists

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/22679382/135241120-5601d2be-be85-4f66-bc61-ff3f4e1b11c2.png)
After:
![image](https://user-images.githubusercontent.com/22679382/135242687-f97913f1-4d41-4d69-92f3-0023bec9c362.png)

**Desktop:**
 - OS: Ubuntu and Android
 - Browser: Firefox, Chrome
 - Version: Firefox 92.0, Chrome 93.0

**Comment by gamebrary** [comment]
Fixed in latest deploy

**Comment by gamebrary** [comment]
@all-contributors please add @rllaquet  for bug
