### ISSUE TITLE
Games on boards and lists do not load

### ISSUE THREAD

**Issue by alec9851** [romancm/gamebrary#262]
**Describe the bug**
Games in lists on boards do not load for me. Neither for my own boards, nor for public boards.
Adding new games does not change anything, nor do those new games show up.

**To Reproduce**
 - Try to access any board.

**Expected behavior**
Load games

**Desktop:**
  - OS: Windows 10
  - Browser: Firefox and MS Edge
  - Version: Firefox 107 and MS Edge 107.0.1418.52

**Additional context**
I've tried deleting cookies, but nothing changes.

**Screenshots**
![1_Public board with games not loading](https://user-images.githubusercontent.com/118633227/202869292-24028d63-efab-4b24-bf4e-e3c3140564a5.png)
![1_Public boards](https://user-images.githubusercontent.com/118633227/202869293-d7693b12-9ad1-4b7e-9450-0a19f8c07ec8.png)
![2_All of my boards](https://user-images.githubusercontent.com/118633227/202869295-9f7c290e-526e-4fce-b5d3-43e34836a3b3.png)
![2_My own board](https://user-images.githubusercontent.com/118633227/202869306-79de95a0-8042-44b9-a9dd-03b399bb4827.png)

**Comment by gamebrary** [comment]
@alec9851 Connection with IGDB has been restored. Game data should now be loading correctly.

![image](https://user-images.githubusercontent.com/60666270/203134034-0e902cf2-997a-46c2-b110-42204889cd02.png)

Thank you for reporting this issue!

**Comment by gamebrary** [comment]
@allcontributors add @alec9851 for bug

**Comment by LittleSia** [comment]
Hello!
I've had exactly the same issue for some days now. But most of the time, the site doesn't load at all.
I'm also using Firefox or Edge.
Thanks for your help!

**Comment by gamebrary** [comment]
Hi @LittleSia, I've made several API changes lately, it is possible that you have an old version of the site cached locally. You can try clearing your cache or doing a [hard refresh on your browser](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache#:~:text=To%20do%20a%20hard%20refresh,click%20the%20'R'%20key.).

**Comment by LittleSia** [comment]
OK, I tried the hard refresh: it doesn't work on Firefox (the site still loading for ages).
On Edge, I can access to the site; the public boards are loading well on the home page but once I'm logged in the public boards in the explore section don't load correctly (as before I can only see the list titles but no games under); same for my own boards.

**Comment by LittleSia** [comment]
Ah, and if I close Edge, open it again and load the site, it doesn't work anymore. I have to delete my cache again to access it.

**Comment by gamebrary** [comment]
Oh I see, I only use mac and linux. If you don't mind. Could you open an issue and specify details (there's an issue template you can fill out). Any screenshots of the browser's console would be useful (Ctrl+Shift+J). I will try to get windows running on a vm or install on a machine to test it.

If you'd like, you could share your user id via email and I can look at the database https://gamebrary.com/account.

Thanks for reporting @LittleSia!


@allcontributors add @LittleSia for bug
