### ISSUE TITLE
Non-Google login option?

### ISSUE THREAD

**Issue by ocdtrekkie** [romancm/gamebrary#54]
I was kind of interested in checking this out, but I don't use Google. And if I did use Google, I wouldn't want to tie my account to an arbitrary app I was looking at. It'd be nice to provide either some alternative login providers (GitHub and Twitter are popular choices) or a third-party independent option.

**Comment by ocdtrekkie** [comment]
As an aside, it'd be nice if your readme and/or website said a little more about the features of the project so I didn't have to log into it to see what it can do. Does it pull data/images from somewhere? If so, where? Is there a way to import the list of digital games into it? Etc.

**Comment by romancmx** [comment]
Those are very valid points, I'm definitely planning on adding twitter and email/pw soon. I'm also planning on adding a proper readme and showcase the tool's features in the landing page.

**Comment by romancm** [comment]
Closing in favor of https://github.com/romancm/gamebrary/issues/86

**Comment by romancm** [comment]
@all-contributors please add @ocdtrekkie for ideas
