### ISSUE TITLE
Cannot drag games in firefox

### ISSUE THREAD

**Issue by apersonnamedmike** [romancm/gamebrary#56]
Just tested with latest stable firefox (65.0.2) vs latest stable chrome (72.0.3626.121) on Windows 10. Dragging games works great in chrome, but won't work at all in firefox.

**Comment by romancm** [comment]
@apersonnamedmike I just tested on 66.0.2 (64-bit) and I wasn't able to reproduce the issue. Closing for now, please let me know if you're able to reproduce it and I'll reopen it.

**Comment by apersonnamedmike** [comment]
Yeah, after having tried it again on firefox 66+, I cannot reproduce it anymore. Glad it's working!

**Comment by romancm** [comment]
@all-contributors please add @apersonnamedmike for bug
