### ISSUE TITLE
New3DS games do not appear under 3DS library

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#57]
New3DS-only games are listed in IGDB as a separate category and thus do not appear in your 3DS gamebrary. Can confirm the bug with Xenoblade Chronicles 3D and Minecraft.

I think the best solution would be just adding them into the 3DS gamepool and not creating a separate New3DS library.

**Comment by romancm** [comment]
Created new issue using new issue template, closing in favor of https://github.com/romancm/gamebrary/issues/57
