### ISSUE TITLE
Screenshot view displays 2 controls for each action

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#63]
![image](https://user-images.githubusercontent.com/29702693/56412414-b3067880-628c-11e9-90f3-bc0e5ec89408.png)

Ubuntu 18.04, Google Chrome 73.0.3683.75 (Official Build) (64-bit).

From a cursory look at the CSS, something is wrong with the :before elements. At the very least, setting ```display:none``` for ```a.close:before```, ```a.next:before```, and ```a.prev:before``` fixes the issue.

![image](https://user-images.githubusercontent.com/29702693/56412711-c1a15f80-628d-11e9-9411-a68e50f94b88.png)

**Comment by romancm** [comment]
Fixed in https://github.com/romancm/gamebrary/releases/tag/v1.15.5
