### ISSUE TITLE
Games no longer load. Can't access the lists

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#64]
![image](https://user-images.githubusercontent.com/29702693/56486360-015f8580-64e0-11e9-98a9-10cad582186a.png)

Tried in Chrome on Linux and Android. The list of platforms shows the number of games in the separate lists but the lists themselves can't be accessed. Tried clearing cash, didn't work.

**Comment by areyouokani** [comment]
Fixed now.

**Comment by romancm** [comment]
API quota was reached for the day due to a spike on traffic, looks like it's back to normal now.

**Comment by romancm** [comment]
@all-contributors please add @areyouokani for question and bug
