### ISSUE TITLE
Authentification error

### ISSUE THREAD

**Issue by OmegaRobert** [romancm/gamebrary#65]
Every time I try to add a game to my wishlist  using the mobile website I get an authentification error. Seems to happen regardless of platform selected.

**Comment by romancm** [comment]
Hmm, it sounds like your session has expired. Try logging out and logging back in.

**Comment by OmegaRobert** [comment]
That fixed it thanks - I'd been having the issue for a few days as I'd closed the tab rather than logging out.

**Comment by romancm** [comment]
I opened a new issue to improve the user experience https://github.com/romancm/gamebrary/issues/66

**Comment by romancm** [comment]
@all-contributors please add @OmegaRobert for bug
