### ISSUE TITLE
Adjustable list width

### ISSUE THREAD

**Issue by romancm** [romancm/gamebrary#69]
# 🌟 Feature

Allow users to adjust the list width

**Comment by mattb555** [comment]
I can take this one next, are you looking for click and drag resizing or more of, given the current view settings, have a user input of some description for x games per row, and then have the list auto-resize to the proper size based on that.

**Comment by romancm** [comment]
More like the latter, I was thinking of introducing a new setting for width so you can have 1, 2, 3 items per row. And use the existing "view" setting to determine the style only (normal, compact, cover)

**Comment by romancm** [comment]
Ultimately open to a y solution, I just think it makes sense to have width and view type as separate settings
