### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by romancm** [romancm/gamebrary#72]
# 🌟 Feature

- [x] Translate all hard-coded strings
- [x] Create translation files for additional languages
- [x] Write translate-json-object script to auto translate to most used languages

Top 10 user languages (from Google Analytics):

🇺🇸 en-us
🇬🇧 en-gb
🇦🇺 en-au
🇵🇱 pl-pl
🇩🇪 de-de
🇨🇦 en-ca
🇪🇸 es-es
🇨🇿 cs-cz
🇫🇷 fr-fr
🇮🇹 it-it

**Comment by Swinkid** [comment]
What languages we thinking?

**Comment by romancm** [comment]
Most popular but I'm thinking about building a script that uses Google translate to create the additional files off of the English file
