### ISSUE TITLE
Twitter and Email auth

### ISSUE THREAD

**Issue by romancm** [romancm/gamebrary#86]
# 🌟 Feature

Add option to login/sign up using twitter account

**Comment by Swinkid** [comment]
What library do you use to handle authentication? Passport? Thinking about trying to do this one

**Comment by romancm** [comment]
Using firebase to handle all authentication https://firebase.google.com/docs/reference/js/firebase.auth

I actually started working on this one yesterday but feel free to tackle it if you really want to 👍

**Comment by Swinkid** [comment]
@romancm No worries, I've started on adding shortcuts instead :)
