### ISSUE TITLE
Bar code scanner

### ISSUE THREAD

**Issue by romancm** [romancm/gamebrary#89]
# 🌟 Feature

https://www.reddit.com/r/PS4/comments/b95hbq/gamebrary_v1130_released/ek2hr7b/?utm_source=share&utm_medium=web2x

**Comment by Swinkid** [comment]
Any thoughts on source of barcode data?

**Comment by romancm** [comment]
I think the only way to get the barcode data is to get it from the user via file upload, luckily I think both iOS and Android give you the option to use your camera when uploading a file.

For decoding the barcode, one option is to use this open source tool https://www.npmjs.com/package/javascript-barcode-reader which should return a UPC number.

The part that I'm not so sure about is converting from UPC to text so we can use it to search.
